### ISSUE TITLE
Implement Historic Price API End Point

### ISSUE THREAD

**Issue by mubaris** [gostudent/coindesk#4]
Implement all the parameters in the historic price API end point.

API Reference - https://www.coindesk.com/api/

**Comment by namantw** [comment]
I will do it

**Comment by mubaris** [comment]
Make sure to document the code

**Comment by namantw** [comment]
@mubaris I am making a new `HistoryPrice` function which takes in start date and end date as parameter and prints all prices from `startDate` to `endDate`. Is that what I am supposed to be doing? Please, correct me if I am wrong.

**Comment by mubaris** [comment]
`HistoricalPrice()` with start date and end date should return an array/slice of structs. Each element in the array should be a struct with 2 fields.

```go
type Price struct {
	date time.Time
	price float64
}
```

That's the main part.

If possible,

* Optional parameter `index` - values either "USD" or "CNY". Defaults to "USD"
* Optional parameter `currency` - Defaults to "USD"
* Create `Yesterday()` to return yesterday's price.

**Comment by namantw** [comment]
Thanks :)

**Comment by namantw** [comment]
![image](https://user-images.githubusercontent.com/31323328/35040489-3c4b3200-fba7-11e7-9753-ef8da084ac3d.png)
Update : The following things are working :  
- made the `HistoryPrice` function
- made the `Yesterday` function
- added example code for new functions
- documented each new function

**Comment by gauthamzz** [comment]
send pr and say update,dont post screenshots
